feat(search): advanced search filters
Arrow-air/svc-storage pull request #38
Opened 2023-02-06 11:10 UTC by owlot

Includes:
 - advanced search filter implementation
 - client-grpc rust-doc improvements

Closes #34

2023-02-07 17:09 UTC, romanmandryk requested changes

2023-02-07 17:32 UTC, owlot commented on client-grpc/src/grpc.rs
> +            PredicateOperator::NotIs => "NOT_IS",
I thought about the order as well, but decided I wanted to keep it aligned with the operator it translates to programmatically (`!=`).
I agree it's a bit confusing with `IS_NULL`/`IS_NOT_NULL`, so I guess it's better to rename it to `EQUALS` and `NOT_EQUALS`

2023-02-07 17:48 UTC, GoodluckH commented on client-grpc/src/grpc.rs
> +            PredicateOperator::NotIs => "NOT_IS",
I think `EQUALS` and `IS` mean different things. So, a cat is a mammal, but a cat does not EQUALS to a mammal. If the predicate translate to `==` or `!=` then I would use `EQUALS` and `NOT_EQUALS`.

2023-02-07 19:43 UTC, owlot commented on client-grpc/src/grpc.rs
> +            PredicateOperator::NotIs => "NOT_IS",
Fixed

2023-02-08 10:10 UTC, romanmandryk approved these changes

2023-02-08 10:11 UTC, merged