R3 Release
Arrow-air/svc-storage pull request #85
Opened 2023-08-27 08:52 UTC by owlot

2023-08-28 21:40 UTC, ServiceDog requested changes

2023-08-28 21:40 UTC, ServiceDog commented on client-grpc/src/macros.rs
> +                    let other_ids = request.other_id_list.unwrap();
Some unhandled unwraps() in the following files:
- server/src/grpc/macros.rs
- client-grpc/src/macros.rs 
- client-grpc/includes/search.rs 
- Mock files under client-grpc/includes/

2023-08-28 21:40 UTC, ServiceDog commented on server/src/postgres/init.rs
>      psql_info!("Creating database tables.");
Some log statements could use the `(fn prepend)` format, see below:

<details>

Test | /// | Location                                                             | Type                 | Statement                                         
---- | --- | -------------------------------------------------------------------- | -------------------- | --------------------------------------------------
 X   |  X  | server/src/main.rs (19)                                              | (no_fn_prepend) msg  | info!("Running database initialization");         
 X   |  X  | server/src/main.rs (19)                                              | punctuation          | info!("Running database initialization");         
 X   |  X  | server/src/main.rs (27)                                              | (no_fn_prepend) msg  | info!("Found argument [init_psql]. Creating dat...
 X   |  X  | server/src/main.rs (29)                                              | (no_fn_prepend) msg  | info!("PSQL Database creation completed.");       
 X   |  X  | server/src/main.rs (34)                                              | (no_fn_prepend) msg  | info!("Found argument [rebuild_psql]. Rebuildin...
 X   |  X  | server/src/main.rs (36)                                              | (no_fn_prepend) msg  | info!("PSQL Rebuild completed.");                 
 X   |  X  | server/src/main.rs (42)                                              | (no_fn_prepend) msg  | info!("Server shutdown.");                        
 X   |  X  | server/src/config.rs (32)                                            | (no_fn_prepend) msg  | log::warn!("Creating Config object with default...
 X   |  X  | server/src/lib.rs (90)                                               | punctuation          | log::warn!("(shutdown_signal) server shutdown for 
 X   |  X  | server/src/postgres/linked_resource.rs (25)                          | punctuation          | psql_debug!("(get_for_ids) start: [{:?}]", ids);  
 X   |  X  | server/src/postgres/linked_resource.rs (38)                          | punctuation          | psql_debug!("(delete_for_ids) start: [{:?}]", ids)
 X   |  X  | server/src/postgres/linked_resource.rs (58)                          | (no_fn_prepend) msg  | psql_debug!("{}", &query);                        
 X   |  X  | server/src/postgres/linked_resource.rs (59)                          | (no_fn_prepend) msg  | psql_debug!("{:?}", &params);                     
 X   |  X  | server/src/postgres/linked_resource.rs (64)                          | (no_fn_prepend) msg  | psql_info!(            "Deleting rows for table...
 X   |  X  | server/src/postgres/linked_resource.rs (81)                          | (no_fn_prepend) msg  | psql_debug!(                            "Remove...
 X   |  X  | server/src/postgres/linked_resource.rs (81)                          | punctuation          | psql_debug!(                            "Removed [
 X   |  X  | server/src/postgres/linked_resource.rs (96)                          | (no_fn_prepend) msg  | psql_debug!(                            "Remove...
 X   |  X  | server/src/postgres/linked_resource.rs (96)                          | punctuation          | psql_debug!(                            "Removed [
 X   |  X  | server/src/postgres/linked_resource.rs (113)                         | punctuation          | psql_debug!("(link_ids) start: [{:?}] replace [{:?
 X   |  X  | server/src/postgres/linked_resource.rs (145)                         | (no_fn_prepend) msg  | psql_debug!("{}", insert_sql);                    
 X   |  X  | server/src/postgres/linked_resource.rs (146)                         | (no_fn_prepend) msg  | psql_debug!("{:?}", &params);                     
 X   |  X  | server/src/postgres/linked_resource.rs (148)                         | (no_fn_prepend) msg  | psql_info!("Update/Insert entry for table [{}]....
 X   |  X  | server/src/postgres/linked_resource.rs (174)                         | punctuation          | psql_debug!("(read) start: [{:?}]", self.try_get_u
 X   |  X  | server/src/postgres/linked_resource.rs (193)                         | (no_fn_prepend) msg  | psql_debug!("{}", query);                         
 X   |  X  | server/src/postgres/linked_resource.rs (194)                         | (no_fn_prepend) msg  | psql_debug!("{:?}", &params);                     
 X   |  X  | server/src/postgres/linked_resource.rs (203)                         | (no_fn_prepend) msg  | psql_info!(            "Fetching row data for t...
 X   |  X  | server/src/postgres/linked_resource.rs (216)                         | punctuation          | psql_debug!("(delete) start: [{:?}]", self.try_get
 X   |  X  | server/src/postgres/linked_resource.rs (224)                         | (no_fn_prepend) msg  | psql_info!(            "Deleting entry from tab...
 X   |  X  | server/src/postgres/linked_resource.rs (240)                         | (no_fn_prepend) msg  | psql_debug!("{}", query);                         
 X   |  X  | server/src/postgres/linked_resource.rs (241)                         | (no_fn_prepend) msg  | psql_debug!("{:?}", &params);                     
 X   |  X  | server/src/postgres/linked_resource.rs (246)                         | (no_fn_prepend) msg  | psql_info!("Removing entry from table [{}].", d...
 X   |  X  | server/src/postgres/linked_resource.rs (264)                         | (no_fn_prepend) msg  | psql_info!("{}", error);                          
 X   |  X  | server/src/postgres/simple_resource_linked.rs (30)                   | punctuation          | psql_debug!("(get_for_ids) start: [{:?}]", ids);  
 X   |  X  | server/src/postgres/simple_resource_linked.rs (43)                   | punctuation          | psql_debug!("(delete_for_ids) start: [{:?}]", ids)
 X   |  X  | server/src/postgres/simple_resource_linked.rs (63)                   | (no_fn_prepend) msg  | psql_debug!("{}", &query);                        
 X   |  X  | server/src/postgres/simple_resource_linked.rs (64)                   | (no_fn_prepend) msg  | psql_debug!("{:?}", &params);                     
 X   |  X  | server/src/postgres/simple_resource_linked.rs (69)                   | (no_fn_prepend) msg  | psql_info!(            "Deleting rows for table...
 X   |  X  | server/src/postgres/simple_resource_linked.rs (86)                   | (no_fn_prepend) msg  | psql_debug!(                            "Remove...
 X   |  X  | server/src/postgres/simple_resource_linked.rs (86)                   | punctuation          | psql_debug!(                            "Removed [
 X   |  X  | server/src/postgres/simple_resource_linked.rs (101)                  | (no_fn_prepend) msg  | psql_debug!(                            "Remove...
 X   |  X  | server/src/postgres/simple_resource_linked.rs (101)                  | punctuation          | psql_debug!(                            "Removed [
 X   |  X  | server/src/postgres/simple_resource_linked.rs (118)                  | punctuation          | psql_debug!("(create) start: [{:?}]", row_data);  
 X   |  X  | server/src/postgres/simple_resource_linked.rs (135)                  | (no_fn_prepend) msg  | psql_debug!("{:?}", &params);                     
 X   |  X  | server/src/postgres/simple_resource_linked.rs (165)                  | punctuation          | psql_debug!("(read) start: [{:?}]", self.try_get_u
 X   |  X  | server/src/postgres/simple_resource_linked.rs (183)                  | punctuation          | psql_debug!("(update) start: [{:?}]", data);      
 X   |  X  | server/src/postgres/simple_resource_linked.rs (207)                  | (no_fn_prepend) msg  | psql_debug!("{}", update_sql);                    
 X   |  X  | server/src/postgres/simple_resource_linked.rs (209)                  | (no_fn_prepend) msg  | psql_debug!("{:?}", &params);                     
 X   |  X  | server/src/postgres/simple_resource_linked.rs (215)                  | (no_fn_prepend) msg  | psql_info!(            "Updating entry in table...
 X   |  X  | server/ [...]

2023-08-28 21:40 UTC, ServiceDog commented on server/src/postgres/simple_resource_linked.rs
> +        // TODO(R3): Move this to 2 separate functions which can be used in other places as well
Got some TODO(R3) throughout:

<details>

Test  | Location                                            | Statement                                         
----- | --------------------------------------------------- | --------------------------------------------------
  X   | server/src/postgres/linked_resource.rs (71)         | // TODO(R3): Move this to 2 separate functions ...
  X   | server/src/postgres/linked_resource.rs (164)        | /// TODO: use `#![feature(async_fn_in_trait)]` ...
  X   | server/src/postgres/linked_resource.rs (175)        | //TODO(R3): implement shared memcache here to g...
  X   | server/src/postgres/linked_resource.rs (256)        | //TODO(R3): flush shared memcache for this reso...
  X   | server/src/postgres/simple_resource_linked.rs (76)  | // TODO(R3): Move this to 2 separate functions ...
  X   | server/src/postgres/simple_resource_linked.rs (152) | /// TODO: use `#![feature(async_fn_in_trait)]` ...
  X   | server/src/postgres/simple_resource_linked.rs (166) | //TODO(R3): implement shared memcache here to g...
  X   | server/src/postgres/simple_resource_linked.rs (219) | //TODO(R3): flush shared memcache for this reso...
  X   | server/src/postgres/simple_resource_linked.rs (294) | //TODO(R3): flush shared memcache for this reso...
  X   | server/src/postgres/simple_resource_linked.rs (338) | //TODO(R3): flush shared memcache for this reso...
  X   | server/src/postgres/mod.rs (223)                    | //TODO(R3): provide metrics, eg: self.metrics.p...
  X   | server/src/postgres/simple_resource.rs (84)         | /// TODO: use `#![feature(async_fn_in_trait)]` ...
  X   | server/src/postgres/simple_resource.rs (98)         | //TODO(R3): implement shared memcache here to g...
  X   | server/src/postgres/simple_resource.rs (151)        | //TODO(R3): flush shared memcache for this reso...
  X   | server/src/postgres/simple_resource.rs (226)        | //TODO(R3): flush shared memcache for this reso...
  X   | server/src/postgres/simple_resource.rs (270)        | //TODO(R3): flush shared memcache for this reso...
  X   | server/src/resources/scanner/mod.rs (73)            | // TODO(R3) After groups are implemented, add o...
  X   | client-grpc/examples/grpc.rs (184)                  | // Get acquire and deliver fields - TODO 

</details>

2023-08-28 21:47 UTC, ServiceDog requested changes

2023-08-28 21:47 UTC, ServiceDog commented on server/Cargo.toml
>  ordered-float       = "3.3.0"
3.3

2023-08-28 21:50 UTC, ServiceDog commented
## Documents
- [ ] ICD
  - [ ] Current interfaces (grpc & rest)
  - [ ] Current relevant document links
- [ ] SDD
  - [ ] Description of grpc & rest handler implementations
  - [ ] Current sequence diagrams where applicable
  - [ ] Current relevant document links
- [ ] CONOPS
  - [ ] Current information
  - [ ] Bibliography (if any citations)
- [x] README (see svc-cargo for example)
  - [x] Badges
  - [x] Accurate installation instructions
  - [x] Current links to other documents
  - [x] Arrow DAO links
- [x] Any instance of :construction: should genuinely be under construction

## Code (not applicable to examples/ folder)
- [ ] No unhandled unwrap()s
- [x] Accurate (!) code comments on all functions
- [x] No `# Arguments` and `# Returns` in function comments
- [x] Function arguments checked where possible
- [x] Sufficient logger (info, warn, and debug) messages
- [x] Sensible Types (unsigned vs. signed)
- [x] No `#[allow(dead_code)]` without good reason
- [ ] End all error, info, and debug messages with punctuation (periods, etc.)
- [ ] No FIXMEs or TODOs without a projected release (`TODO R4: etc.`)

## ~~REST API~~ N/A

## Cargo.toml(s)
- [x] Package versions correct
- [ ] No minor versions specified
- ~~Links to crates.io package, not git branch~~ N/A
- [x] Must have `license-file = "LICENSE"` under `[package]`

2023-09-23 21:48 UTC, owlot commented
Will close this PR and open a new one from a branch with fixes

2023-09-23 21:48 UTC, closed without merging